// Code generated by options-gen. DO NOT EDIT.
package protogen

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// MetadataDir is the directory containing CloudStack API metadata
func WithMetadataDir(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.metadataDir = opt

	}
}

// OutputDir is the directory where generated files will be written
func WithOutputDir(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.outputDir = opt

	}
}

func (o *Options) Validate() error {
	return nil
}
