package main


	// this application needs to parse the buf.yaml file, find the third-party-deps in the second marked section of the file

	// clone them with git, using cmd.Exec

	// grab the path referenced in the file 

	/// the file is gonna look like this: 

// 	# yaml-language-server: $schema=https://json.schemastore.org/buf.json

// version: v2

// ....

// ---
// # yaml-language-server: $schema=https://json.schemastore.org/any.json

// buf3pd:
//     path: gen/proto-remotes
//     deps:
//       - type: git
//         repo: github.com/walteh/bufbuild
//         path: protovalidate/proto/protovalidate
//         ref: heads/main


// we just need to support git as a type right now 

// also, we need to create a new file next to the buf.yaml file, called buf3pd.lock.yaml

// we need to keep track of the hashes from our download of the remote repos, and the commit hashes - smaple:
// # Generated by buf. DO NOT EDIT.
// version: v2
// deps:
//   - name: buf.build/googleapis/googleapis
//     commit: 61b203b9a9164be9a834f58c37be6f62
//     digest: b5:7811a98b35bd2e4ae5c3ac73c8b3d9ae429f3a790da15de188dc98fc2b77d6bb10e45711f14903af9553fa9821dff256054f2e4b7795789265bc476bec2f088c


